### ISSUE TITLE
Table name does not have underscore

### ISSUE THREAD

**Issue by KenTandrian** [EcoSenseID/EcoSense-CloudSQL#10]
https://github.com/EcoSenseID/EcoSense-CloudSQL/blob/2c7bcac4ca76fce329cf0e4c49a6b817b0683a68/DB.md?plain=1#L35-L42

@kenjimarwies Ini nama tabelnya memang ga ada underscore?

**Comment by kenjimarwies** [comment]
solved, mmg ada underscore nya, typo maap
