### ISSUE TITLE
Change terminology used in our system

### ISSUE THREAD

**Issue by KenTandrian** [EcoSenseID/EcoSense-CloudSQL#11]
Mengacu pada API Requirements, kita ganti terminologi ya, jadi nama table atau attribute coba disesuaikan kembali:
1. `comment` ganti jadi `reply` (kalo plural jadi `replies` tergantung konteks aja)
2. `like` ganti jadi `support` (sesuaikan juga pluralnya)

**Comment by KenTandrian** [comment]
Ini belum? @kenjimarwies

**Comment by kenjimarwies** [comment]
di attribute gada sih, di nama table aj n udh revised y @KenTandrian

**Comment by KenTandrian** [comment]
Masih ada yang belum diganti ya, coba cek kembali @kenjimarwies

**Comment by kenjimarwies** [comment]
oh yg tabel comments supports, sori wait

**Comment by kenjimarwies** [comment]
btw cek line bntr bole ken? @KenTandrian

**Comment by KenTandrian** [comment]
Okay, kalau sudah revisi please tell me ya @kenjimarwies

**Comment by kenjimarwies** [comment]
ini udh di revisi ya @KenTandrian

**Comment by KenTandrian** [comment]
Okay solved
