### ISSUE TITLE
Wrong attribute name, should be `id_campaign`

### ISSUE THREAD

**Issue by KenTandrian** [EcoSenseID/EcoSense-CloudSQL#13]
https://github.com/EcoSenseID/EcoSense-CloudSQL/blob/8353fb677532e30ce97d5ebb482e807f6716e611/DB.md?plain=1#L86-L94

Tolong dicek kembali attribute `id_campaign` ya @kenjimarwies

**Comment by KenTandrian** [comment]
Terus, `id_campaign` itu harusnya FK ke `campaigns(id)` @kenjimarwies

**Comment by kenjimarwies** [comment]
revised done ya

**Comment by KenTandrian** [comment]
@kenjimarwies attribute id_campaign masih salah nama deh?

**Comment by kenjimarwies** [comment]
oh mau buat id_campaign ga mau pke s, sori g perhatiin sep gw revisi bntr

**Comment by KenTandrian** [comment]
Iya, karena id kampanye yang disimpan hanya satu untuk setiap entry data. Kalo dibuat plural beda arti

**Comment by kenjimarwies** [comment]
done ya
