### ISSUE TITLE
Please add serial `id` in `reward_claims` table

### ISSUE THREAD

**Issue by KenTandrian** [EcoSenseID/EcoSense-CloudSQL#14]
https://github.com/EcoSenseID/EcoSense-CloudSQL/blob/8353fb677532e30ce97d5ebb482e807f6716e611/DB.md?plain=1#L118-L124

@kenjimarwies nanti bantu tambahkan primary key `id` di `reward_claims` ini ya

**Comment by KenTandrian** [comment]
Ohya, untuk rewards yang kategori E-Wallet, kita perlu simpan data `email`, `walletType`, dan `walletNumber` pas user-nya klaim, kira-kira mau simpan gimana ya menurut u? @kenjimarwies

**Comment by kenjimarwies** [comment]
primary key nya udh added ya @KenTandrian

**Comment by kenjimarwies** [comment]
yg rewards ada kategories apa aj selain e-wallet?  i think tmbh aj wallet type di table reward_categories, baru tar buat table "walletType" yang isinya ada id 'PK", email, sm wallet Number

gimn menurut lu?? @KenTandrian

**Comment by KenTandrian** [comment]
So far kategorinya ada e-wallet, donation, dan voucher.

**Comment by KenTandrian** [comment]
Tapi masalahnya, 1 wallet type bukan hanya ada 1 email dan 1 wallet number. Contoh, aku pake OVO dengan email a@gmail.com dan nomor HP 0812345678. Nanti orang lain bisa aja pake walletType OVO juga dengan email berbeda dan nomor HP berbeda. Itu gimana?

**Comment by KenTandrian** [comment]
Ohya, id_rewards di sini tolong ganti ke singular juga ya

**Comment by kenjimarwies** [comment]
gw cb buat pake array of string deh y, gtw bs jalan ato engga but gw liat ada yg pernah coba pake array of string ada yg bs ad yg engga

**Comment by kenjimarwies** [comment]
jadi mungkin tar dibuat tabel baru walletType, isi nya ad 
id PK
name VARCHAR 
wallet array of string []
phone_number []
gt?

**Comment by KenTandrian** [comment]
Kenapa gitu? Misalnya aku mau ambil data `wallet_type`, `email` dan `phone_number` dari seseorang dengan User ID `XXX`, itu gimana caranya?

**Comment by KenTandrian** [comment]
> gw cb buat pake array of string deh y, gtw bs jalan ato engga but gw liat ada yg pernah coba pake array of string ada yg bs ad yg engga

I think we don't need array of string sih, malah merumitkan diri sendiri nanti wkwk

**Comment by kenjimarwies** [comment]
> Ohya, `id_rewards` di sini tolong ganti ke singular juga ya

ini done ya

**Comment by kenjimarwies** [comment]
> Ohya, untuk rewards yang kategori E-Wallet, kita perlu simpan data `email`, `walletType`, dan `walletNumber` pas user-nya klaim, kira-kira mau simpan gimana ya menurut u? @kenjimarwies

yg kategori 'e-wallet' ini nnti mau dipakai pas di 'rewards', 'reward_categories' atau 'reward-claims'?? pas kapan kita mau simpan data si 'e-wallet' dari user ini?? @KenTandrian

**Comment by kenjimarwies** [comment]
> Ohya, untuk rewards yang kategori E-Wallet, kita perlu simpan data `email`, `walletType`, dan `walletNumber` pas user-nya klaim, kira-kira mau simpan gimana ya menurut u? @kenjimarwies

yg kategori 'e-wallet' ini nnti mau dipakai pas di `rewards`, `reward_categories` atau `reward-claims`?? pas kapan kita mau simpan data si `e-wallet` dari user ini?? @KenTandrian

**Comment by KenTandrian** [comment]
Aku kurang paham maksud dari "dipakai" ini wkwk nanti kita bahas deh ya pas meeting

**Comment by kenjimarwies** [comment]
cb cek ya ken, udh ku add @KenTandrian

**Comment by KenTandrian** [comment]
Eh buat nullable dong

**Comment by kenjimarwies** [comment]
Yg ap nullable sorry?

**Comment by KenTandrian** [comment]
3 attribute itu.. tapi sepertinya ga not null pun gapapa deh, string kosong aja nanti
