### ISSUE TITLE
Table not showing correctly

### ISSUE THREAD

**Issue by KenTandrian** [EcoSenseID/EcoSense-CloudSQL#15]
https://github.com/EcoSenseID/EcoSense-CloudSQL/blob/1c0f8f27c038cd4dad4140c372fda9b42fd76327/DB.md?plain=1#L149-L154

Ini coba dicek @kenjimarwies kok pas preview file markdown-nya hancur tabelnya ya?

**Comment by KenTandrian** [comment]
![image](https://user-images.githubusercontent.com/60643640/197139315-0a43cf0d-c949-49b9-b2e4-3cf473893b7a.png)
Ini screenshotnya

**Comment by kenjimarwies** [comment]
solved

**Comment by kenjimarwies** [comment]
solved
