### ISSUE TITLE
Change `task` to `mission`

### ISSUE THREAD

**Issue by KenTandrian** [EcoSenseID/EcoSense-CloudSQL#16]
https://github.com/EcoSenseID/EcoSense-CloudSQL/blob/8353fb677532e30ce97d5ebb482e807f6716e611/DB.md?plain=1#L35-L42

https://github.com/EcoSenseID/EcoSense-CloudSQL/blob/8353fb677532e30ce97d5ebb482e807f6716e611/DB.md?plain=1#L69-L77

**Comment by KenTandrian** [comment]
Is this done?

**Comment by kenjimarwies** [comment]
> Is this done?

yg ini done

**Comment by kenjimarwies** [comment]
> https://github.com/EcoSenseID/EcoSense-CloudSQL/blob/768486c00e8f56d665419648c0504ef74fdeced3/DB.md?plain=1#L61-L69
> 
> 
> @kenjimarwies `id_missions` tolong jadikan singular ya biar ga rancu. Soalnya itu hanya mengacu ke 1 mission.

ok wait

**Comment by kenjimarwies** [comment]
done revissed ya

> > https://github.com/EcoSenseID/EcoSense-CloudSQL/blob/768486c00e8f56d665419648c0504ef74fdeced3/DB.md?plain=1#L61-L69
> > 
> > @kenjimarwies `id_missions` tolong jadikan singular ya biar ga rancu. Soalnya itu hanya mengacu ke 1 mission.
> 
> ok wait

done ya

**Comment by KenTandrian** [comment]
Okay thanks!
