### ISSUE TITLE
Add data to table `reward_categories`

### ISSUE THREAD

**Issue by KenTandrian** [EcoSenseID/EcoSense-CloudSQL#17]
Tolong isi tabelnya pake data ini ya:

| id | name | 
| :---: | :---: | 
| 1 | e-wallet | 
| 2 | donation | 
| 3 | voucher |

**Comment by kenjimarwies** [comment]
ini di add aj kan brarti data yang lama ga perlu dibuang ??

**Comment by KenTandrian** [comment]
Iya dibuang saja ya data lamanya, we won't be using those.

**Comment by kenjimarwies** [comment]
noted, will be update now

**Comment by kenjimarwies** [comment]
added to db ya ken @KenTandrian

**Comment by KenTandrian** [comment]
Okay thanks!
