### ISSUE TITLE
Wrong table name in Line 92

### ISSUE THREAD

**Issue by KenTandrian** [EcoSenseID/EcoSense-CloudSQL#6]
https://github.com/EcoSenseID/EcoSense-CloudSQL/blob/2c7bcac4ca76fce329cf0e4c49a6b817b0683a68/DB.md?plain=1#L92-L99

@kenjimarwies Ini tabel apa ya? Kok nama tabelnya ga ada

**Comment by KenTandrian** [comment]
Btw, memang tabelnya ga ada primary key id gitu ya? @kenjimarwies

**Comment by kenjimarwies** [comment]
table name mmg stories, typo salah ketik, untuk primary key mmg ada udh ku add.

for id kampanye ntr gw update sql nya dlu then aku edit disini plus stories likes no need ya brarti so aku buang di db nya @KenTandrian

**Comment by KenTandrian** [comment]
Please check Issue https://github.com/EcoSenseID/EcoSense-CloudSQL/issues/13 ya
