### ISSUE TITLE
Lack of several attributes in rewards table

### ISSUE THREAD

**Issue by KenTandrian** [EcoSenseID/EcoSense-CloudSQL#7]
https://github.com/EcoSenseID/EcoSense-CloudSQL/blob/2c7bcac4ca76fce329cf0e4c49a6b817b0683a68/DB.md?plain=1#L112-L120

@kenjimarwies Please add `title` and `how_to_use` ya, karena ada di [API requirements](https://github.com/EcoSenseID/EcoSense-ApiRequirements/blob/31e334372396f1efac8312b255e21a5f4769c7fa/response_samples/get%20reward%20detail.json) dari tim MD 😁

Terus, aku baru notice kalo di requirements, `terms_and_conditions` dan `how_to_use` itu bentuknya `Array of strings`. Coba check apakah di kedua attributes itu bisa dibuat jadi array di database ya.

Untuk attribute `isRedeemed` tidak perlu di database ya, nanti dari backend API akan query ke tabel `claimed_rewards` aja

**Comment by kenjimarwies** [comment]
noted bakal gw ganti asap

**Comment by KenTandrian** [comment]
Attribute `title` mana ya? Kok belum ada @kenjimarwies

**Comment by KenTandrian** [comment]
Ohya, please add a new attribute `partner` ya, untuk nama pembuat rewardnya (e.g. Netflix, Greenpeace) @kenjimarwies

**Comment by KenTandrian** [comment]
Sama satu lagi attribute `max_redeem` untuk jumlah redeem maksimal (e.g. 0, 1, 2, 3, dst)

**Comment by kenjimarwies** [comment]
btw ini partner brarti manual masukkin kan nama pembuat nya ntr (pake varchar aj brarti) atau nama pembuat nya udh simpan di db jadi ntr tinggal pilih? @KenTandrian

**Comment by KenTandrian** [comment]
Bentuk string ya

**Comment by kenjimarwies** [comment]
brarti yg partner, how_to_use sm terms_and_conditions mau buat array of strings? brsn wa riset ada yg pernah buat, bs dicoba sih klo mau buat array of strings?? mau gw cb buat aj kah @KenTandrian

**Comment by KenTandrian** [comment]
Partner kenapa array?

**Comment by KenTandrian** [comment]
Kalau `how_to_use` dan `terms_and_conditions` tidak perlu `array of strings` lagi, ikut pembahasan kemarin di meeting aja pake `\n`

**Comment by kenjimarwies** [comment]
ok sep done
