### ISSUE TITLE
Typo (?) @ Line 139

### ISSUE THREAD

**Issue by KenTandrian** [EcoSenseID/EcoSense-CloudSQL#8]
https://github.com/EcoSenseID/EcoSense-CloudSQL/blob/2c7bcac4ca76fce329cf0e4c49a6b817b0683a68/DB.md?plain=1#L136-L140

@kenjimarwies 
1. Attribute `id_category` harusnya ga ada spasi kan ya?
2. Di belakang Line 140 harusnya ada garis `|` lagi ga sih?

**Comment by kenjimarwies** [comment]
solved
